POST http://localhost:3333/esportivo
Content-Type: application/json

{
    "modelo": "DBS V12",
    "marca": "Aston Martin",
    "potencia": "510 hp"
}

###

GET http://localhost:3333/esportivo

###

GET http://localhost:3333/esportivo?search=GT86

###

PUT http://localhost:3333/esportivos/808acbe6-c87f-4a84-b5ed-50ec19021805
Content-Type: application/json

{
    "modelo": "GT86",
    "marca": "Toyota",
    "potencia": "200"
}

###

DELETE http://localhost:3333/esportivos/a924e1fe-af7d-4900-abf8-c557c6d9d843